title: Albert Monfà. Linux and Open Source Technologies.
description: >
    Hi! I’m Albert, systems engineer specialized in open source.
    Nowadays I’m based in Saigon, working remotely as SRE (Site Reliability Engineering)
    for a relevant financial services company established in Europe.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Albert Monfà
author-img: albert-monfa.jpg
about-author: Hi! I’m Albert, systems engineer specialized in open source. Nowadays I’m based in Saigon, working remotely as SRE (Site Reliability Engineering) for a relevant financial services company established in Europe.
social-github: albertmonfa
social-linkedin: albertmonfa

# Disqus
discus-identifier: albert-monfa

# Tracker
analytics: UA-75053420-1

# Build Settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
